var categorylist = [
    {
        id:'1',
        value:'鲜果区'
    },
    {
        id:'2',
        value:'礼品区'
    },
    {
        id:'3',
        value:'人群'
    },
    {
        id:'4',
        value:'场合'
    },
    {
        id:'5',
        value:'品牌'
    },
    {
        id:'6',
        value:'原产地'
    },
    {
        id:'7',
        value:'限时抢购'
    },
];

var indexlist  = [
    {
        id:'0001',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'佳沛新西兰金奇异果（S号）',
        price:'89'
    },
    {
        id:'0002',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'佳沛新西兰金奇异果（L号）',
        price:'90'
    },
    {
        id:'0003',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'香蕉dsada',
        price:'98'
    }
];

var certlist = [
    {
        order_id:'',
        good_id:'',
        good_title:'1111111111111111111',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'191',
        good_num:'2'

    },
    {
        order_id:'',
        good_id:'',
        good_title:'22222222222222',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'192',
        good_num:'2'

    },
    {
        order_id:'',
        good_id:'',
        good_title:'dsadasdad',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'192',
        good_num:'3'
    }
];
