var categorylist = [
    {
        id:'1',
        title:'鲜果区',
        value:[
            {
                list_id:'1',
                name:'苹果'
            },   
            {
                list_id:'2',
                name:'香蕉'
            },    
            {
                list_id:'3',
                name:'梨子'
            }
        ]
    },
    {
        id:'2',
        title:'礼品区',
        value:[
            {
                list_id:'4',
                name:'水果果篮'
            },   
            {
                list_id:'5',
                name:'果蔬'
            },    
            {
                list_id:'6',
                name:'充值卡'
            }
        ]
    },
    {
        id:'3',
        title:'人群',
        value:[
            {
                list_id:'7',
                name:'儿童'
            },   
            {
                list_id:'8',
                name:'孕妇'
            }
        ]
    },
    {
        id:'4',
        title:'场合',
        value:[
            {
                list_id:'9',
                name:'生日'
            },   
            {
                list_id:'10',
                name:'结婚'
            }
        ]
    },
    {
        id:'5',
        title:'品牌',
        value:[
            {
                list_id:'11',
                name:'进口'
            }
        ]
    },
    {
        id:'6',
        title:'原产地',
        value:[
            
            {
                list_id:'13',
                name:'美国'
            },   
            {
                list_id:'14',
                name:'新西兰'
            }
        ]
    },
    {
        id:'7',
        title:'限时抢购',
        value:[
            {
                list_id:'15',
                name:'限时'
            }
        ]
    }
];

var indexlist  = [
    {
        pro_id:'0001',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'佳沛新西兰金奇异果（S号）',
        price:'89'
    },
    {
        pro_id:'0001',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'佳沛新西兰金奇异果（L号）',
        price:'90'
    },
    {
        pro_id:'0001',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'香蕉dsada',
        price:'98'
    }
];

var listitems = [
    {
        pro_id:'0001',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'西兰金奇异果（1号）',
        price:'89'
    },
    {
        pro_id:'0002',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'西兰金奇异果（2号）',
        price:'89'
    },
    {
        pro_id:'0003',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'兰金奇异果（3号）',
        price:'89'
    },
    {
        pro_id:'0004',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'兰金奇异果（4号）',
        price:'8913'
    },
    {
        pro_id:'0005',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'兰金奇异果（5号）',
        price:'89'
    },
    {
        pro_id:'0006',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'兰金奇异果（6号）',
        price:'89'
    },
    {
        pro_id:'0007',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'西兰金奇异果（7号）',
        price:'89'
    }
];



var certlist = [
    {
        order_id:'',
        good_id:'',
        good_title:'1111111111111111111',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'191',
        good_num:'2'

    },
    {
        order_id:'',
        good_id:'',
        good_title:'22222222222222',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'192',
        good_num:'2'

    },
    {
        order_id:'',
        good_id:'',
        good_title:'dsadasdad',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'192',
        good_num:'3'
    }
];
