var categorylist = [
    {
        id:'1',
        title:'鲜果区',
        value:[
            {
                list_id:'1',
                name:'11111111'
            },   
            {
                list_id:'2',
                name:'222222'
            },    
            {
                list_id:'3',
                name:'33333333333'
            }
        ]
    },
    {
        id:'2',
        title:'礼品区',
        value:[
            {
                list_id:'4',
                name:'444444444'
            },   
            {
                list_id:'5',
                name:'5555555555'
            },    
            {
                list_id:'6',
                name:'6666666666666'
            }
        ]
    },
    {
        id:'3',
        title:'人群',
        value:[]
    },
    {
        id:'4',
        title:'场合',
        value:[]
    },
    {
        id:'5',
        title:'品牌',
        value:[]
    },
    {
        id:'6',
        title:'原产地',
        value:[]
    },
    {
        id:'7',
        title:'限时抢购',
        value:[]
    }
];

var indexlist  = [
    {
        id:'0001',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'佳沛新西兰金奇异果（S号）',
        price:'89'
    },
    {
        id:'0002',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'佳沛新西兰金奇异果（L号）',
        price:'90'
    },
    {
        id:'0003',
        img_src:'http://static.fruitday.com/product_pic/2233/1/1-180x180-2233.jpg',
        title:'香蕉dsada',
        price:'98'
    }
];

var certlist = [
    {
        order_id:'',
        good_id:'',
        good_title:'1111111111111111111',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'191',
        good_num:'2'

    },
    {
        order_id:'',
        good_id:'',
        good_title:'22222222222222',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'192',
        good_num:'2'

    },
    {
        order_id:'',
        good_id:'',
        good_title:'dsadasdad',
        good_img_src:'http://cdn.ifanr.cn/wp-content/uploads/ta-thumbnails-cache/220x130-c/2014/2/402590-1.jpg',
        good_dec:'dkjsajdlkajdlkajdjaljdlajsldkjakl',
        good_price:'192',
        good_num:'3'
    }
];
